### PR TITLE
Fix-Bug: Opening same domain again and again in V2

### LINKED ISSUE #171: [bug] Few Bugs in v2
### Header
- The home button redirects to a new tab, which should refresh the page.
- The hackathon button is redirecting to the roadmaps repo. This confuses the user. If there is no Hackathon repo kind of, you can remove the link from there.
- YouTube button redirects to Kunal's YT channel and there is another YT button in the body which is redirecting to WeMakeDev's YT channel, for a better user experience please provide buttons for both of them. 
### Body
- Roadmaps card- `Roadmaps` button is redirecting to Kunal's courses playlist
- In Partner with us, both Contact us and See Partner testimonial buttons are redirecting to the events repo.
### Footer
-  Inn Join our community, both Telegram and Discord buttons are redirecting to the events repo

### To Reproduce

_No response_

### Expected Behavior

_No response_

### Screenshot/ Video

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sboy99**
## Fixes Issue

This PR fixes the following issues:
- Clicking Home does not reloads the page

closes #171 

## Changes proposed
- Modified Navbar data in V2
- Enabled Conditional rendering for nav links
Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarised content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots 
N/A
Add all the screenshots which support your changes

### CODE REVIEW

**Comment by AnuragThePathak** [comment]
Did we not merge a similar issue 1-2 days ago?

**Comment by sboy99** [comment]
Yes you did but previously I worked on v1 but currently v2 is active with the same old code so the problem still exists. Although it doesn't open a new tab but it still targets the same domain and reloads the page while checking home.
To reproduce goto inspect then network tab and try clicking home you will see it reloads all the contents.
This is not a problem for high speed internet as of now but it the website grows or a user with low internet speed can face weird issue.
Thats why I fixed the same but now its on v2

File: src/v2/components/common/navbar/index.jsx [hunk 1]
```diff
@@ -39,12 +48,10 @@ const Navbar = () => {
               </li>
             );
           })}
-          <li>
-          
-          </li>
+          <li></li>
```
Comment (AnuragThePathak) [inline src/v2/components/common/navbar/index.jsx:51]: Purpose of existence of the empty `li` tag?

Comment (sboy99) [reply src/v2/components/common/navbar/index.jsx:51]: I didn't changed it that was there in v2 so didn't change it. I kept it as it was. I changed the essential path to effect

Comment (sboy99) [reply src/v2/components/common/navbar/index.jsx:51]: If you want me I can remove that as well, just let me know

Comment (AnuragThePathak) [reply src/v2/components/common/navbar/index.jsx:51]: All right then remove it.

Comment (AnuragThePathak) [reply src/v2/components/common/navbar/index.jsx:51]: Eh I think the best thing we should do is to keep it the way it was earlier, i.e. git shouldn't show the changes. Removal or modification of that shouldn't be part of this PR.

Comment (AnuragThePathak) [reply src/v2/components/common/navbar/index.jsx:51]: And kindly amend the changes to the recent commit instead of creating a new one.

Comment (sboy99) [reply src/v2/components/common/navbar/index.jsx:51]: As I use prettier plugin, the changes were made automatically, anyhow I think rather than keep it as it was, removing might be a better option as it will increase the code quality and also enhance the code readability to other contributors as well in future.
Waiting for your response...

Comment (sboy99) [reply src/v2/components/common/navbar/index.jsx:51]: See this empty `li` is also taking empty space in `navlinks`
  
Screenshot from 2022-12-08 20-08-47

Comment (sboy99) [reply src/v2/components/common/navbar/index.jsx:51]: Removing the `li` element also removes the space that was contained by `li`
Screenshot from 2022-12-08 20-14-00

Comment (sboy99) [reply src/v2/components/common/navbar/index.jsx:51]: If you consider removal would be a better option then let me know, and please mention should I amend in recent commit or should I commit a new one.

Comment (AnuragThePathak) [reply src/v2/components/common/navbar/index.jsx:51]: Keep `li`, that was willingly added for design purpose 😀.

**Review by AnuragThePathak — APPROVED** [review]
LGTM
