### PR TITLE
Bug fixed/#376 Events page linked

### LINKED ISSUE #376: [bug] Redirect Wrong page
### Describe the bug

On the home page event button currently redirect to we make devs GitHub page. it should be redirected to https://wemakedevs.org/events page

### To Reproduce

_No response_

### Expected Behavior

_No response_

### Screenshot/ Video

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Bawanthathilan**
## Fixes Issue

This PR fixes the following issues:

closes #376 

-  Courses button linked to the courses page and events to the event page in the home page in the new tab
-  Ongoing event button linked to the ongoing event page

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

### CODE REVIEW

File: src/components/home/Hero/index.jsx [hunk 1]
```diff
@@ -33,10 +33,7 @@ const Hero = () => {
           >
             Mentorship
           </ArrowLink>
-          <ArrowLink
-            as={ButtonLink}
-            href='https://github.com/WeMakeDevs/events'
-          >
+          <ArrowLink as={ButtonLink} href='/events' target='_blank'>
```
Comment (Chandraprakash-Darji) [inline src/components/home/Hero/index.jsx:36]: Pass the prop `openNewTab` instead of `target='_blank'`

File: src/components/layout/ColumnSection/index.jsx [hunk 2]
```diff
@@ -42,6 +42,7 @@ const ColumnSection = ({
                 href={buttonLink.href}
                 className={styles.btn}
                 as={ButtonLink}
+                target={buttonLink.target}
```
Comment (Chandraprakash-Darji) [inline src/components/layout/ColumnSection/index.jsx:45]: same here

**Review by Chandraprakash-Darji — CHANGES_REQUESTED** [review]

File: src/components/layout/ColumnSection/index.jsx (hunk 2 above)
Comment (Bawanthathilan) [reply src/components/layout/ColumnSection/index.jsx:45]: ok

Comment (Bawanthathilan) [reply src/components/layout/ColumnSection/index.jsx]: fixed

File: .gitignore [hunk 3]
```diff
@@ -18,6 +18,8 @@
 .env.test.local
 .env.production.local
 
+
```
Comment (Chandraprakash-Darji) [inline .gitignore:21]: undo this change

**Review by Chandraprakash-Darji — CHANGES_REQUESTED** [review]

File: .gitignore [hunk 4]
```diff
@@ -18,6 +18,7 @@
...
```
Comment (Chandraprakash-Darji) [inline .gitignore:21]: still there is changes

**Review by Chandraprakash-Darji — CHANGES_REQUESTED** [review]

File: .gitignore (hunk 4 above)
Comment (Bawanthathilan) [reply .gitignore]: check now
