### PR TITLE
Our Students work at section aliened

### LINKED ISSUE #267: [bug] Our Students work at section not aliened well
### Describe the bug

Our students work at section heading is stick to above section.

### To Reproduce

Go to OUR STUDENTS WORK AT Section

### Expected Behavior

Should give some padding from top as we given to other components.

### Screenshot/ Video

image

### Additional context

Please assign this to me

### PR DESCRIPTION
**Pull request by AbhiPatel10**
## Fixes Issue

This PR fixes the following issues:

closes #267

## Changes proposed

Here comes all the changes proposed through this PR

Convert Heading All Capital Word to first letter in uppercase and the remaining letters in lowercase.

Change in css to add padding-block.

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

Add all the screenshots which support your changes

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
@AbhiPatel10 Add the 3 more companys `virtusa`, `samsung` and `cisco`.

**Comment by AbhiPatel10** [comment]
I Have added Above 3 company logos please check it.

image

**Review by bhavyastar — CHANGES_REQUESTED** [review]
@AbhiPatel10 Hey Can you fix the latest logo size?

**Comment by AbhiPatel10** [comment]
Now looks good ?

image

**Comment by Chandraprakash-Darji** [comment]
@bhavyastar what do you think about making all the logo's grayscale

**Comment by Chandraprakash-Darji** [comment]
@AbhiPatel10 add `razorpay` to componay section

File: src/components/home/Work/index.jsx [hunk 1]
```diff
@@ -7,18 +7,27 @@ import Amazon from '../../../assets/home/amazon.svg';
...
-        <h2 className='h1'>OUR STUDENTS WORK AT</h2>
+        <h2 className='h1'>Our Students Work at</h2>
         <hr className={clsx('styled-hr', styles.headingWorkLine)} />
         <div className={styles.workImg}>
           <img className={styles.workGoogle} src={Google} alt='google' />
           <img className={styles.workAmazon} src={Amazon} alt='amazon' />
           <img className={styles.workMicro} src={Microsoft} alt='microsoft' />
           <img className={styles.workAdobe} src={Adobe} alt='adobe' />
         </div>
+        <div className={styles.workImg2}>
```
Comment (ManishBisht777) [inline src/components/home/Work/index.jsx:26]: Instead of making a separate div for separate lines, we can include the images in `workimg` div and set flex-wrap:wrap

Comment (AbhiPatel10) [reply src/components/home/Work/index.jsx]: > @AbhiPatel10 add `razorpay` to company section

Added `Razorpay` Logo

**Comment by AbhiPatel10** [comment]
> @AbhiPatel10 add `razorpay` to company section

Added `Razorpay` Logo.

File: src/components/home/Work/index.jsx (hunk 1 above)
Comment (AbhiPatel10) [reply src/components/home/Work/index.jsx]: Yes I have remove second section and use the flexbox.

**Comment by AbhiPatel10** [comment]
image

**Comment by Chandraprakash-Darji** [comment]
@AbhiPatel10 Thanks for the contribution

**Comment by AbhiPatel10** [comment]
It's my pleasure, looking forward to contribute more in WeMakeDevs 🚀

**Comment by AbhiPatel10** [comment]
> @AbhiPatel10 Thanks for the contribution

It's my pleasure, looking forward to contribute more in WeMakeDevs 🚀
